import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { defineConfig } from "cypress";
import fix from "cypress-on-fix";
import { configureXrayPlugin, syncFeatureFile } from "cypress-xray-plugin";

// For reading environment variables from a .env file.
// See: https://www.npmjs.com/package/dotenv
import "dotenv/config";

export default defineConfig({
  env: process.env,
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      // Order matters here:
      // The Cucumber plugin must run its event listeners first before the Xray plugin can upload
      // result reports generated by the Cucumber plugin.
      await addCucumberPreprocessorPlugin(fixedOn, config);
      await configureXrayPlugin(fixedOn, config, {
        jira: {
          // Placeholder.
          projectKey: "CYP",
          url: "https://example.org",
        },
        cucumber: {
          featureFileExtension: ".feature",
          uploadFeatures: true,
          prefixes: {
            test: "MyScenarioPrefix:",
            precondition: "MyPreconditionPrefix:",
          },
        },
      });
      fixedOn("file:preprocessor", async (file) => {
        await syncFeatureFile(file);
        const cucumberPlugin = createBundler({
          plugins: [createEsbuildPlugin(config)],
        });
        return cucumberPlugin(file);
      });
      return config;
    },
    specPattern: "**/*.feature",
  },
});
